Custom request headers
tushuhei/sphinxcontrib-screenshot pull request #45
Opened 2024-12-28 21:05 UTC by azmeuk

This PR implements the `:header:` and the `screenshot_default_headers` configuration parameter.

fixes #23

2025-01-04 15:19 UTC, azmeuk commented
After a thousand tries, I finally got the CI green @tushuhei

2025-01-04 18:08 UTC, tushuhei requested changes

2025-01-04 18:08 UTC, tushuhei commented on pyproject.toml
> +    "pytesseract",
It seems this library is not used anymore

2025-01-04 18:08 UTC, tushuhei commented on .github/workflows/unit-test.yml
> +                fd.write("pytest=" + "\n".join(files))
nit. Perhaps we can rename this variable to `imgs` or something similar to indicate failed images, since `steps.pytest.outputs.pytest` is repetitive.

2025-01-04 18:08 UTC, tushuhei commented on tests/test_headers.py
> +    image_regression.check(fd.read(), diff_threshold=0.5)
Could you add `# Tolerance of 0.5%` as a comment at the end of this line? Due to this method's API design, it's unclear whether 0.5 represents 0.5% or 50%.

2025-01-04 18:09 UTC, tushuhei commented
Thank you for your hard work! I added some nit comments.

2025-01-04 19:38 UTC, azmeuk commented
This is done :)

2025-01-05 02:30 UTC, tushuhei approved these changes

2025-01-05 02:31 UTC, merged